spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb  # 启用 H2 内存数据库
    username: sa
    password:
    type: com.zaxxer.hikari.HikariDataSource
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.javatoai.springdemo.pojo.entity
  configuration:
    map-underscore-to-camel-case: true
  base-package: com.javatoai.springdemo.mapper

mybatis-plus:
  mapper-locations: classpath:/mapper/*/*.xml
  configuration:
    cache-enabled: false # 启用缓存
