spring:
  ai:
    openai:
      chat:
        enabled: false
      api-key: sk-zk26a0bc3bb97f0e90217d15b4cd7d9a02b67a84e59c444f
      base-url: https://api.zhizengzeng.com/v1
    dashscope:
      api-key: sk-f8f1ac4f3e9f472aaff8545f80f4850f
      chat:
        options:
          model: deepseek-r1
