spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://server:3306/springbootdemo?useUnicode=true&acharacterEncoding=utf-8&auseSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 最大连接池数量
      maxPoolSize: 20
      # 最小空闲线程数量
      minIdle: 10
      # 配置获取连接等待超时的时间
      connectionTimeout: 30000
      # 校验超时时间
      validationTimeout: 5000
      # 空闲连接存活最大时间，默认10分钟
      idleTimeout: 600000
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
      maxLifetime: 1800000
      # 连接测试query（配置检测连接是否有效）
      connectionTestQuery: SELECT 1
      # 多久检查一次连接的活性
      keepaliveTime: 30000
  config:
    activate:
      on-profile: serve


mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.javatoai.springdemo.pojo.entity
  configuration:
    map-underscore-to-camel-case: true
  base-package: com.javatoai.springdemo.mapper

mybatis-plus:
  mapper-locations: classpath:/mapper/*/*.xml
  configuration:
    cache-enabled: false # 启用缓存
